project:
  type: website

website:
  favicon: favicon.png
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/diarmuidbrady/
      - icon: instagram
        href: https://instagram.com/thetenaciouslife_
format:
  html:
    theme: cosmo
    css: styles.css



